#!/bin/sh -e
# OUT (CC flags...) : Sets up a 'reasonably sensible' compile.

WHERE_AM_I="`readlink -f "$0"`"
export KIP32_SDK="`dirname "$WHERE_AM_I"`"
TRANSPILER="$KIP32_SDK/../target/debug/sci32_udon"

OUTPUT_FILE="$1"
shift

riscv64-unknown-elf-gcc -mabi=ilp32 -march=rv32i -nostartfiles -nolibc -ffreestanding "$@" -T "$KIP32_SDK/kip32.ld" -o "$OUTPUT_FILE.elf"
../kip32/target/debug/sci32_udon "$OUTPUT_FILE.elf" --inc "$KIP32_SDK/log_syscall.uasm" --ecall _ecall -o "$OUTPUT_FILE"
