#!/bin/sh
cargo fmt
riscv64-unknown-elf-gcc -O3 -mabi=ilp32 -march=rv32i -nostartfiles -nolibc -ffreestanding science.c -o science.elf -T science.ld
objdump -D science.elf > science.lst
cargo run > ../kvtools/Assets/science.uasm
